default:
  image: node:20-alpine
  tags:
    - frontend

stages:
  - build
  - deploy

build:
  only:
    - master
    - dev
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
      - .yarn
      - .next/cache/
  stage: build
  script:
    - yarn install --ignore-scripts
    - yarn run build
  artifacts:
    expire_in: 1 week
    paths:
      - out

deploy:
  only:
    - master
    - dev
  tags:
    - frontend
  image: node:alpine
  stage: deploy
  script:
    - apk add --no-cache rsync
    - export PROJECT_ID=$(node -p "require('./package.json').project_id")
    - export PROJECT_YEAR=$(node -p "'20$PROJECT_ID'.substr(0,4)")
    - echo $PROJECT_ID
    - echo $PROJECT_YEAR
    - OUTPUT_DIR=/mnt/diskstation/web/dev/$PROJECT_YEAR/$PROJECT_ID
    - rsync -rv out/ $OUTPUT_DIR/htdocs/
    - chmod -R a+rwX $OUTPUT_DIR/htdocs/ || true
